### ISSUE TITLE
Fix Security Alerts!

### ISSUE THREAD

**Issue by truedat101** [IoTone/ProjectGyr#1]
https://github.com/IoTone/ProjectGyr/network/alerts

Please fix these as soon as possible.

**Comment by truedat101** [comment]
@davicitoafc let me know when this is done and I'll tag this release as done.

**Comment by davicitoafc** [comment]
The link is broken so I don't know what errors you see, but on my end I dont see errors at all.

**Comment by truedat101** [comment]
Must be an admin rights thing.  


![security_gyr](https://user-images.githubusercontent.com/64202/51795684-8fa3c400-219c-11e9-80d7-0972c35a7754.PNG)


rack
opened on Nov 15, 2018 by GitHub • Gemfile.lock
moderate severity
rails-html-sanitizer
opened on Nov 14, 2018 by GitHub • Gemfile.lock
moderate severity
nokogiri
opened on Nov 14, 2018 by GitHub • Gemfile.lock
moderate severity
loofah
opened on Nov 14, 2018 by GitHub • Gemfile.lock
moderate severity
sinatra
opened on Nov 14, 2018 by GitHub • Gemfile.lock
high severity

**Comment by truedat101** [comment]
So did you push changes?  Nothing to review yet.

**Comment by truedat101** [comment]
Ok will review.
